export enum ExceptionTitleList {
  BadRequest = 'badRequest',
  DeleteDefaultError = 'deleteDefaultError',
  EmailAlreadyExists = 'emailAlreadyExists',
  EmailNotFound = 'emailNotFound',
  Forbidden = 'Forbidden',
  ImageNotExists = 'imageNotExists',
  IncorrectOldPassword = 'incorrectOldPassword',
  InvalidCredentials = 'invalidCredentials',
  InvalidRefreshToken = 'invalidRefreshToken',
  NeedLoginViaProvider = 'needLoginViaProvider',
  NotFound = 'Not Found',
  OldPasswordRequired = 'oldPAsswordRequired',
  RefreshTokenExpired = 'refreshTokenExpired',
  RoleNotExists = 'roleNotExists',
  StatusNotExists = 'statusNotExists',
  TooManyTries = 'tooManyTries',
  Unauthorized = 'Unauthorized',
  UserInactive = 'userInactive',
  UserNotFound = 'userNotFound',
}
